### ISSUE TITLE
field_ui_base_route does not add tabs to the bundle edit page.

### ISSUE THREAD

**Issue by Jaesin** [Jaesin/content_entity_base#52]
The pattern being used for the `field_ui_base_route`(`entity.foo_type.edit_form`) is not adding the field ui tabs to the edit form page.

**Comment by Jaesin** [comment]
This is because the entity type edifor form is missing from the lints.task.yml file.

```
entity.example_type.edit_form:
  title: Edit
  route_name: entity.example_type.edit_form
  base_route: entity.example_type.edit_form
```
